#:schema node_modules/wrangler/config-schema.json
name = "remix-2503-of-gestao-de-contratos"
compatibility_date = "2026-05-11"

[assets]
directory = "./dist"

[vars]
# Variáveis de ambiente podem ser adicionadas aqui

