-- DIAGNOSTICO: colunas que as migrations acrescentam e este banco nao tem
--
-- Gerado por scripts/diagnostico/gerar-diagnostico.mjs a partir das
-- 275 migrations do repositorio. Para atualizar, rode o script.
--
-- E a checagem que faltava: o defeito do checklist era uma COLUNA ausente
-- (`checklist_modelos.exigir_geolocalizacao`), e nenhuma verificacao de tabela
-- pegaria isso. Tabela inteira ausente aparece na outra consulta, entao aqui ela
-- e ignorada para o resultado nao repetir o mesmo problema.
--
-- NAO ALTERA NADA: so le o catalogo do Postgres.
-- Tabelas apagadas de proposito por alguma migration ficam de fora da conta.

WITH esperadas(tabela, coluna) AS (VALUES
  ('atividades_planejamento', 'is_principal'),
  ('checklist_aplicacoes', 'itens_criticos_nao_conformes'),
  ('checklist_aplicacoes', 'reprovado_por_item_critico'),
  ('checklist_evidencias', 'capturada_em'),
  ('checklist_evidencias', 'latitude'),
  ('checklist_evidencias', 'longitude'),
  ('checklist_evidencias', 'motivo_sem_geo'),
  ('checklist_evidencias', 'origem_captura'),
  ('checklist_evidencias', 'precisao_metros'),
  ('checklist_itens', 'critico'),
  ('checklist_modelos', 'bloquear_fora_raio'),
  ('checklist_modelos', 'exigir_geolocalizacao'),
  ('checklist_modelos', 'latitude_alvo'),
  ('checklist_modelos', 'longitude_alvo'),
  ('checklist_modelos', 'raio_permitido_metros'),
  ('clientes', 'cep'),
  ('contratos', 'numero_contrato'),
  ('custo_real_erp', 'categoria_analise'),
  ('custo_real_erp', 'categoria_confirmada'),
  ('custo_real_erp', 'categoria_sugerida_ia'),
  ('diario_fotos', 'capturada_em'),
  ('diario_fotos', 'diario_producao_id'),
  ('diario_fotos', 'latitude'),
  ('diario_fotos', 'longitude'),
  ('diario_fotos', 'motivo_sem_geo'),
  ('diario_fotos', 'ordem'),
  ('diario_fotos', 'origem_captura'),
  ('diario_fotos', 'precisao_metros'),
  ('diario_fotos', 'thumb_600_url'),
  ('diario_fotos', 'thumb_url'),
  ('diario_veiculos', 'km_final'),
  ('diario_veiculos', 'km_inicial'),
  ('diarios_obra', 'clima'),
  ('diarios_obra', 'municipio'),
  ('diarios_obra', 'status_ativo'),
  ('diarios_obra', 'uf'),
  ('empresas', 'logo_url'),
  ('escopo_itens', 'item_lpu_id'),
  ('faturamentos_conta_azul', 'descricao'),
  ('faturamentos_conta_azul', 'empresa_id'),
  ('faturamentos_conta_azul', 'numero_venda'),
  ('faturamentos_conta_azul', 'payload_json'),
  ('faturamentos_conta_azul', 'valor_aberto'),
  ('faturamentos_conta_azul', 'valor_baixado'),
  ('flash_category_mapping', 'flash_category'),
  ('flash_category_mapping', 'flash_cost_center'),
  ('flash_category_mapping', 'flash_description_pattern'),
  ('flash_category_mapping', 'last_feedback_at'),
  ('flash_category_mapping', 'last_feedback_source'),
  ('flash_category_mapping', 'learned'),
  ('flash_category_mapping', 'manual_confirmations'),
  ('flash_integration_logs', 'conta_azul_protocolo'),
  ('flash_integration_logs', 'conta_azul_transaction_id'),
  ('flash_integration_logs', 'flash_transaction_id'),
  ('flash_integration_logs', 'reconciliado'),
  ('flash_integration_logs', 'reconciliado_at'),
  ('flash_normalizacao', 'conta_azul_payload'),
  ('flash_normalizacao', 'flash_type_detectado'),
  ('flash_normalizacao', 'mapping_id_usado'),
  ('flash_normalizacao', 'motivo'),
  ('flash_transactions_raw', 'amount'),
  ('flash_transactions_raw', 'transaction_date'),
  ('fornecedores', 'avaliacoes_total'),
  ('fornecedores', 'cep'),
  ('fornecedores', 'complemento'),
  ('fornecedores', 'municipio'),
  ('fornecedores', 'preferido'),
  ('fornecedores', 'score_prazo'),
  ('fornecedores', 'score_preco'),
  ('fornecedores', 'score_qualidade'),
  ('fornecedores', 'score_responsividade'),
  ('fornecedores', 'uf'),
  ('frentes_obra', 'site_id'),
  ('itens_lpu', 'bdi'),
  ('itens_lpu', 'projeto_id'),
  ('lancamentos_faturamento', 'numero_po'),
  ('lancamentos_medicao', 'anexo_url'),
  ('lancamentos_medicao', 'capa_url'),
  ('lancamentos_medicao', 'data_resposta'),
  ('lancamentos_medicao', 'fotos_por_pagina'),
  ('lancamentos_medicao', 'legenda_padrao_fotos'),
  ('lancamentos_medicao', 'logo_empresa_url'),
  ('lancamentos_medicao', 'modo_somente_fotos'),
  ('lancamentos_medicao', 'mostrar_lpu'),
  ('lancamentos_medicao', 'mostrar_valores_site'),
  ('lancamentos_medicao', 'numero_po'),
  ('lancamentos_medicao', 'observacao_acompanhamento'),
  ('lancamentos_medicao', 'periodo_fim'),
  ('lancamentos_medicao', 'periodo_inicio'),
  ('lancamentos_medicao', 'quantidade_aprovada'),
  ('lancamentos_medicao', 'quantidade_pendente'),
  ('lancamentos_medicao', 'quantidade_rejeitada'),
  ('lancamentos_producao', 'municipio'),
  ('lancamentos_producao', 'uf'),
  ('mapeamento_categorias_erp', 'ativo'),
  ('medicao_report_photo_captions', 'ordem'),
  ('profiles', 'aprovado'),
  ('profiles', 'cargo'),
  ('profiles', 'cpf'),
  ('profiles', 'data_nascimento'),
  ('profiles', 'pode_aprovar_compra'),
  ('profiles', 'pode_criar_cotacao'),
  ('profiles', 'pode_criar_pedido'),
  ('profiles', 'pode_receber_compra'),
  ('profiles', 'pode_rejeitar_compra'),
  ('profiles', 'sexo'),
  ('projeto_impostos', 'perc_csll'),
  ('projeto_impostos', 'perc_irpj'),
  ('projeto_impostos', 'perc_total_impostos'),
  ('projetos', 'area_analise'),
  ('projetos', 'area_id'),
  ('projetos', 'cliente_id'),
  ('projetos', 'contrato_id'),
  ('projetos', 'contrato_ids'),
  ('projetos', 'empresa_id'),
  ('projetos', 'forecast_data'),
  ('projetos', 'valor_total'),
  ('recursos', 'cargo'),
  ('recursos', 'empresa_id'),
  ('recursos', 'placa'),
  ('recursos', 'status'),
  ('requisicoes_compra', 'tipo_compra'),
  ('requisicoes_compra', 'workflow_status'),
  ('sgsst_apr_medidas', 'data_implementacao'),
  ('sgsst_apr_medidas', 'data_verificacao'),
  ('sgsst_apr_medidas', 'forma_acompanhamento'),
  ('sgsst_apr_medidas', 'observacao_verificacao'),
  ('sgsst_apr_medidas', 'resultado_verificacao'),
  ('sgsst_apr_medidas', 'verificador_id'),
  ('sgsst_asos', 'crm_coordenador'),
  ('sgsst_asos', 'data_exame_clinico'),
  ('sgsst_asos', 'descricao_riscos'),
  ('sgsst_asos', 'empresa_cnpj'),
  ('sgsst_asos', 'empresa_nome'),
  ('sgsst_asos', 'if'),
  ('sgsst_asos', 'medico_coordenador'),
  ('sgsst_asos', 'nova_funcao'),
  ('sgsst_asos', 'riscos_marcados'),
  ('sgsst_asos', 'sem_risco_especifico'),
  ('sgsst_asos', 'unidade'),
  ('sgsst_colaborador_dados', 'centro_custo'),
  ('sgsst_colaborador_dados', 'cep'),
  ('sgsst_colaborador_dados', 'cnh_categoria'),
  ('sgsst_colaborador_dados', 'cnh_numero'),
  ('sgsst_colaborador_dados', 'cnh_validade'),
  ('sgsst_colaborador_dados', 'cpf'),
  ('sgsst_colaborador_dados', 'data_nascimento'),
  ('sgsst_colaborador_dados', 'email'),
  ('sgsst_colaborador_dados', 'endereco'),
  ('sgsst_colaborador_dados', 'endereco_complemento'),
  ('sgsst_colaborador_dados', 'foto_r2_key'),
  ('sgsst_colaborador_dados', 'foto_url'),
  ('sgsst_colaborador_dados', 'genero'),
  ('sgsst_colaborador_dados', 'nome'),
  ('sgsst_colaborador_dados', 'projeto_id'),
  ('sgsst_colaborador_dados', 'rg'),
  ('sgsst_colaborador_dados', 'tamanho_calca'),
  ('sgsst_colaborador_dados', 'tamanho_calcado'),
  ('sgsst_colaborador_dados', 'tamanho_camisa'),
  ('sgsst_colaborador_dados', 'telefone'),
  ('sgsst_epi_entregas', 'orientacao_observacao'),
  ('sgsst_epi_entregas', 'orientacao_uso'),
  ('sgsst_epis', 'abaixo_minimo'),
  ('sgsst_epis', 'exige_higienizacao'),
  ('sgsst_epis', 'higienizacao_periodicidade_dias'),
  ('sgsst_epis', 'vida_util_meses'),
  ('sgsst_exames', 'clinica_id'),
  ('sgsst_exames', 'data_agendada'),
  ('sgsst_exames', 'hora_agendada'),
  ('sgsst_exames', 'motivo_remarcacao'),
  ('sgsst_exames', 'natureza'),
  ('sgsst_exames', 'ordem_exame'),
  ('sgsst_exames', 'remarcacoes'),
  ('sgsst_exames', 'resultado_classificacao'),
  ('sgsst_incidentes', 'cat_emitida'),
  ('sgsst_incidentes', 'data_afastamento'),
  ('sgsst_incidentes', 'data_retorno'),
  ('sgsst_incidentes', 'dias_debitados'),
  ('sgsst_incidentes', 'dias_perdidos'),
  ('sgsst_pcmso', 'agravos_saude'),
  ('sgsst_pcmso', 'ano_referencia'),
  ('sgsst_pcmso', 'criterios_conduta'),
  ('sgsst_pcmso_exames', 'base_legal'),
  ('sgsst_pcmso_exames', 'faixa_etaria'),
  ('sgsst_pcmso_exames', 'ghe_id'),
  ('sgsst_pcmso_exames', 'justificativa_tecnica'),
  ('sgsst_pcmso_exames', 'risco_catalogo_id'),
  ('sgsst_pgr', 'empresa_cnpj'),
  ('sgsst_pgr', 'empresa_nome'),
  ('sgsst_pgr', 'metodologia'),
  ('sgsst_pgr', 'periodicidade_revisao_meses'),
  ('sgsst_pgr', 'registro_responsavel'),
  ('sgsst_pgr', 'responsavel_tecnico'),
  ('sgsst_pgr', 'versao'),
  ('sgsst_pgr_inventario', 'data_medicao'),
  ('sgsst_pgr_inventario', 'descricao_local'),
  ('sgsst_pgr_inventario', 'ghe_id'),
  ('sgsst_pgr_inventario', 'grupos_expostos'),
  ('sgsst_pgr_inventario', 'intensidade_medida'),
  ('sgsst_pgr_inventario', 'limite_tolerancia_aplicado'),
  ('sgsst_pgr_inventario', 'metodologia_medicao'),
  ('sgsst_pgr_inventario', 'resultado_avaliacao'),
  ('sgsst_pgr_inventario', 'tecnica_avaliacao'),
  ('sgsst_pgr_inventario', 'tempo_exposicao'),
  ('sgsst_pgr_inventario', 'tipo_exposicao'),
  ('sgsst_pgr_inventario', 'unidade_medida'),
  ('sgsst_pgr_medidas_controle', 'data_verificacao'),
  ('sgsst_pgr_medidas_controle', 'forma_acompanhamento'),
  ('sgsst_pgr_medidas_controle', 'observacao_verificacao'),
  ('sgsst_pgr_medidas_controle', 'resultado_verificacao'),
  ('sgsst_pgr_medidas_controle', 'verificador_id'),
  ('sgsst_pt', 'bloqueio_energias'),
  ('sgsst_pt', 'plano_resgate'),
  ('sgsst_pt', 'validade_fim'),
  ('sgsst_pt', 'ventilacao_adotada'),
  ('sgsst_riscos_catalogo', 'base_legal'),
  ('sgsst_riscos_catalogo', 'limite_tolerancia'),
  ('sgsst_riscos_catalogo', 'tecnica_avaliacao'),
  ('sgsst_riscos_catalogo', 'unidade_medida'),
  ('sgsst_treinamentos', 'base_legal'),
  ('sgsst_treinamentos', 'conteudo_programatico'),
  ('sgsst_treinamentos_turmas', 'empresa_cnpj'),
  ('sgsst_treinamentos_turmas', 'empresa_nome'),
  ('sgsst_treinamentos_turmas', 'instrutor_qualificacao'),
  ('sgsst_treinamentos_turmas', 'registro_responsavel'),
  ('sgsst_treinamentos_turmas', 'responsavel_tecnico'),
  ('sgsst_treinamentos_turmas', 'tipo_treinamento'),
  ('signature_signers', 'primeiro_acesso_em'),
  ('signature_signers', 'recusa_motivo'),
  ('signature_signers', 'recusado_em'),
  ('signature_signers', 'token')
)
SELECT e.tabela, e.coluna
  FROM esperadas e
  JOIN pg_tables t
    ON t.schemaname = 'public' AND t.tablename = e.tabela
  LEFT JOIN information_schema.columns c
    ON c.table_schema = 'public'
   AND c.table_name = e.tabela
   AND c.column_name = e.coluna
 WHERE c.column_name IS NULL
 ORDER BY 1, 2;
