-- DIAGNOSTICO: tabelas que as migrations declaram e este banco nao tem
--
-- POR QUE ISTO EXISTE
--
-- O repositorio tem 238 arquivos de migration e o banco nao registra todos
-- como aplicados. Ja aconteceu tres vezes de um recurso falhar em producao
-- porque a migration dele nunca rodou: signature_signers (fila de assinatura),
-- as colunas de geolocalizacao do checklist e a tabela checklist_qrcodes.
--
-- Nos tres casos a descoberta foi por tentativa e erro, um erro por vez.
-- Esta consulta responde tudo de uma vez.
--
-- NAO ALTERA NADA. So le o catalogo do Postgres e lista o que falta.
-- Cada linha do resultado e uma tabela que algum codigo da aplicacao espera
-- encontrar e que nao existe aqui.
--
-- Para regerar depois de novas migrations:
--
--   grep -rhoiE "CREATE TABLE (IF NOT EXISTS )?public\.[a-z0-9_]+" \
--     supabase/migrations/*.sql | sed -E 's/.*public\.//' | sort -u

WITH esperadas(nome) AS (VALUES
  ('analises_ia'),
  ('areas'),
  ('atividade_recursos'),
  ('atividades_planejamento'),
  ('audit_log'),
  ('checklist_agendamento_execucoes'),
  ('checklist_agendamentos'),
  ('checklist_aplicacoes'),
  ('checklist_evidencias'),
  ('checklist_geolocalizacoes'),
  ('checklist_itens'),
  ('checklist_modelos'),
  ('checklist_notificacoes'),
  ('checklist_planos_acao'),
  ('checklist_qrcodes'),
  ('checklist_regras'),
  ('checklist_respostas'),
  ('checklist_secoes'),
  ('clientes'),
  ('contaazul_tokens'),
  ('contratos'),
  ('cotacao_itens'),
  ('cotacoes'),
  ('custo_real_erp'),
  ('dependencias_atividade'),
  ('diario_campo_fotos'),
  ('diario_equipamentos'),
  ('diario_equipe'),
  ('diario_fotos'),
  ('diario_producao'),
  ('diario_veiculos'),
  ('diarios_campo'),
  ('diarios_obra'),
  ('empresas'),
  ('escopo_itens'),
  ('escopos_historico'),
  ('faturamento_itens'),
  ('faturamentos'),
  ('faturamentos_conta_azul'),
  ('fca_eventos'),
  ('flash_category_mapping'),
  ('flash_integration_logs'),
  ('flash_normalizacao'),
  ('flash_transactions_raw'),
  ('fornecedores'),
  ('foto_geolocalizacao_ajustes'),
  ('foto_geolocalizacao_cache'),
  ('frentes_obra'),
  ('frentes_recursos'),
  ('integracoes_erp_config'),
  ('integracoes_erp_log'),
  ('item_lpu_bdi_mensal'),
  ('itens_lpu'),
  ('lancamentos_faturamento'),
  ('lancamentos_medicao'),
  ('lancamentos_producao'),
  ('mapeamento_categorias_erp'),
  ('medicao_exports'),
  ('medicao_report_photo_captions'),
  ('medicao_status_historico'),
  ('mkp_parametros'),
  ('municipios_ibge'),
  ('notificacoes'),
  ('orcamento_projetos'),
  ('pedido_itens'),
  ('pedidos_compra'),
  ('profiles'),
  ('projeto_impostos'),
  ('projetos'),
  ('recurso_alocacoes'),
  ('recurso_custos'),
  ('recursos'),
  ('report_templates'),
  ('requisicao_historico'),
  ('requisicao_itens'),
  ('requisicoes_compra'),
  ('sc_alcada_aprovadores'),
  ('sc_alcadas'),
  ('sc_historico'),
  ('sc_itens'),
  ('sc_locais'),
  ('sgsst_apr'),
  ('sgsst_apr_etapas'),
  ('sgsst_apr_historico'),
  ('sgsst_apr_medidas'),
  ('sgsst_apr_participantes'),
  ('sgsst_apr_riscos'),
  ('sgsst_aso_exames'),
  ('sgsst_asos'),
  ('sgsst_asos_historico'),
  ('sgsst_cats'),
  ('sgsst_clinicas'),
  ('sgsst_colaborador_dados'),
  ('sgsst_colaborador_treinamentos'),
  ('sgsst_documentos'),
  ('sgsst_documentos_historico'),
  ('sgsst_documentos_versoes'),
  ('sgsst_epi_devolucoes'),
  ('sgsst_epi_entregas'),
  ('sgsst_epi_historico'),
  ('sgsst_epi_manutencoes'),
  ('sgsst_epis'),
  ('sgsst_evidencias'),
  ('sgsst_exames'),
  ('sgsst_funcao_epis'),
  ('sgsst_funcao_riscos'),
  ('sgsst_funcao_treinamentos'),
  ('sgsst_funcoes'),
  ('sgsst_ghe'),
  ('sgsst_ghe_funcoes'),
  ('sgsst_hht'),
  ('sgsst_incidentes'),
  ('sgsst_incidentes_acoes'),
  ('sgsst_incidentes_envolvidos'),
  ('sgsst_incidentes_historico'),
  ('sgsst_incidentes_investigacao'),
  ('sgsst_inspecoes'),
  ('sgsst_inspecoes_historico'),
  ('sgsst_inspecoes_itens'),
  ('sgsst_inspecoes_nao_conformidades'),
  ('sgsst_nao_conformidades'),
  ('sgsst_nao_conformidades_acoes'),
  ('sgsst_nao_conformidades_historico'),
  ('sgsst_pcmso'),
  ('sgsst_pcmso_exames'),
  ('sgsst_pcmso_historico'),
  ('sgsst_pgr'),
  ('sgsst_pgr_historico'),
  ('sgsst_pgr_inventario'),
  ('sgsst_pgr_inventario_funcoes'),
  ('sgsst_pgr_medidas_controle'),
  ('sgsst_pt'),
  ('sgsst_pt_checklist'),
  ('sgsst_pt_historico'),
  ('sgsst_pt_medicoes_atmosfera'),
  ('sgsst_pt_medidas'),
  ('sgsst_pt_participantes'),
  ('sgsst_pt_riscos'),
  ('sgsst_riscos_catalogo'),
  ('sgsst_treinamentos'),
  ('sgsst_treinamentos_historico'),
  ('sgsst_treinamentos_participantes'),
  ('sgsst_treinamentos_turmas'),
  ('signature_documents'),
  ('signature_events'),
  ('signature_requests'),
  ('signature_signers'),
  ('sites'),
  ('solicitacoes_exclusao_conta'),
  ('timeline_eventos'),
  ('user_permissions'),
  ('user_preferences'),
  ('user_roles'),
  ('user_sites')
)
SELECT e.nome AS tabela_ausente
  FROM esperadas e
  LEFT JOIN pg_tables t
    ON t.schemaname = 'public' AND t.tablename = e.nome
 WHERE t.tablename IS NULL
 ORDER BY 1;
